# tasks file for docker-cacti
- name: cloning docker-cacti repository please wait ... 
  ansible.builtin.git:
    repo: https://github.com/scline/docker-cacti.git
    dest: /opt/docker-cacti
    version: master
    force: yes

- name: changing default sensitive environment variables value
  template:
    src: cacti_single_install.j2
    dest: '{{ docker_compose_dir }}/{{ cacti_deployment }}'
    owner: root
    group: root
    mode: 0644
  become: true

- name: bringing up cacti containers by "docker-compose -f {{ cacti_deployment }} up -d"
  community.docker.docker_compose:
    project_src: '{{ docker_compose_dir }}'
    files: '{{ cacti_deployment }}'
    build: no #set to yes on first run
  register: output