# tasks file for docker-zabbix
- name: cloning docker-zabbix repository please wait ... 
  ansible.builtin.git:
    repo: https://github.com/zabbix/zabbix-docker.git
    dest: /opt/docker-zabbix
    version: '{{ zabbix_branch_version }}'
    force: yes

- name: changing default sensitive environment variables value
  template:
    src: docker-compose_v3_alpine_mysql_latest.j2
    dest: '{{ docker_compose_dir }}/{{ zabbix_compose_file }}'
    owner: root
    group: root
    mode: 0644
  become: true

- name: bringing up zabbix containers by "docker-compose -f {{ zabbix_compose_file }} up -d "
  community.docker.docker_compose:
    project_src: '{{ docker_compose_dir }}'
    files: '{{ zabbix_compose_file }}'
